/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views;

import Commons.ConnectData;
import Controllers.DAO.GroupsPerDAO;
import Emtitys.Employers;
import Views.Account.InforAcc;
import Views.Employees.EmployeesManager;
import Views.PayManger.PaysManager;
import Views.ProductsManager.ProductsManager;
import java.awt.Cursor;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.awt.event.WindowAdapter;
import java.awt.event.WindowEvent;
import java.sql.Connection;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.List;
import javax.swing.Timer;
import jdk.nashorn.internal.runtime.ListAdapter;

/**
 *
 * @author NGUYEN DUC DUY
 */
public class Manager extends javax.swing.JFrame {

    /**
     * Creates new form Manager
     */
    ConnectData connect = new ConnectData();
    Connection c = connect.Connecting();
    Emtitys.Employers em;
    GroupsPerDAO GPD;

    public Manager(Emtitys.Employers e) {
        setTime();
        initComponents();                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                     
        setTitle("Phần mềm quản lý siêu thị (" + e.getName() + ")");
        setDefaultCloseOperation(this.DISPOSE_ON_CLOSE);
// nhận tài khoản khi đăng nhập
        this.em = e;
        this.GPD = new GroupsPerDAO(c);

        MethodCommon c = new MethodCommon(getClass(), this, "icon-logo-X-green16.png");
        setLocationRelativeTo(null);
        showAcc();
//        
        defaultRoles();
//        
        roles();

    }
//  sét thời gian

    private void setTime() {
        DateFormat dateFormat = new SimpleDateFormat("dd/MM/yyy");
        DateFormat timeFormat = new SimpleDateFormat("HH:mm:ss");
        int interval = 1000; // 1000 ms

        new Timer(interval, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                Calendar now = Calendar.getInstance();
                if (now.get(Calendar.DAY_OF_WEEK) == 1) {
                    dayOfWeek.setText("CN");
                } else {
                    dayOfWeek.setText("Thứ " + String.valueOf(now.get(Calendar.DAY_OF_WEEK)));
                }

                time.setText(timeFormat.format(now.getTime()));
                date.setText(dateFormat.format(now.getTime()));
            }
        }).start();

    }
// phương thức hiển thị thông tin tài khoản

    private void showAcc() {
        jAccName.setText(em.getName());
    }
//  phân quyền
    // mặc định

    private void defaultRoles() {
        jProduct.setVisible(false);
        jEmployer.setVisible(false);
        jPay.setVisible(false);

    }

    // phân

    private void roles() {
        List<String> listPAByEm = GPD.listPerActByEm(em.getId());
        for (String listPAByEm1 : listPAByEm) {
            System.out.println(listPAByEm1);
        }
        if (em.getStatus() == 2) {
            jProduct.setVisible(true);
            jEmployer.setVisible(true);
            jPay.setVisible(true);
        } else {
            if (listPAByEm.contains("Pro") || listPAByEm.contains("Cat") || listPAByEm.contains("Unit")) {
                jProduct.setVisible(true);
            }
            if (listPAByEm.contains("Em") || listPAByEm.contains("Per")) {
                jEmployer.setVisible(true);
            }
            if (listPAByEm.contains("Pay") || listPAByEm.contains("Order") || listPAByEm.contains("Couter")) {
                jPay.setVisible(true);
            }
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInteractAcc = new javax.swing.JPopupMenu();
        jInforEm = new javax.swing.JMenuItem();
        jLogout = new javax.swing.JMenuItem();
        jBoxHeader = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        time = new javax.swing.JLabel();
        date = new javax.swing.JLabel();
        dayOfWeek = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jAccName = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jAcc = new javax.swing.JLabel();
        jBoxController = new javax.swing.JPanel();
        jProduct = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jEmployer = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jPay = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();

        jInforEm.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/Male-user-info-icon.png"))); // NOI18N
        jInforEm.setText("Chỉnh sửa tài khoản");
        jInforEm.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jInforEmActionPerformed(evt);
            }
        });
        jInteractAcc.add(jInforEm);

        jLogout.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/Logout-icon.png"))); // NOI18N
        jLogout.setText("Đăng xuất");
        jLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jLogoutActionPerformed(evt);
            }
        });
        jInteractAcc.add(jLogout);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jBoxHeader.setBackground(new java.awt.Color(0, 102, 0));
        jBoxHeader.setForeground(new java.awt.Color(0, 102, 0));

        jPanel1.setBackground(new java.awt.Color(0, 102, 0));

        time.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        time.setForeground(new java.awt.Color(255, 255, 255));
        time.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        time.setText("10:00");
        time.setToolTipText("");
        time.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        date.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        date.setForeground(new java.awt.Color(255, 255, 255));
        date.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        date.setText("10/10/2000");
        date.setVerticalAlignment(javax.swing.SwingConstants.BOTTOM);

        dayOfWeek.setForeground(new java.awt.Color(255, 255, 255));
        dayOfWeek.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dayOfWeek.setText("Thứ 2");
        dayOfWeek.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(dayOfWeek, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(21, 21, 21))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(time, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(date, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(dayOfWeek, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel2.setBackground(new java.awt.Color(0, 102, 0));

        jPanel3.setBackground(new java.awt.Color(0, 102, 0));

        jAccName.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jAccName.setForeground(new java.awt.Color(255, 255, 255));
        jAccName.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        jAccName.setText("Nguyễn Duy");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAccName, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAccName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(0, 102, 0));

        jAcc.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jAcc.setForeground(new java.awt.Color(255, 255, 255));
        jAcc.setText("Tài khoản");
        jAcc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jAccMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAcc, javax.swing.GroupLayout.DEFAULT_SIZE, 77, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jAcc)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jBoxHeaderLayout = new javax.swing.GroupLayout(jBoxHeader);
        jBoxHeader.setLayout(jBoxHeaderLayout);
        jBoxHeaderLayout.setHorizontalGroup(
            jBoxHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jBoxHeaderLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jBoxHeaderLayout.setVerticalGroup(
            jBoxHeaderLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jBoxController.setBackground(new java.awt.Color(255, 255, 255));
        jBoxController.setToolTipText("ok");

        jProduct.setBackground(new java.awt.Color(63, 175, 100));
        jProduct.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jProductMouseMoved(evt);
            }
        });
        jProduct.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jProductMousePressed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Sản phẩm");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/sale-icon.png"))); // NOI18N

        javax.swing.GroupLayout jProductLayout = new javax.swing.GroupLayout(jProduct);
        jProduct.setLayout(jProductLayout);
        jProductLayout.setHorizontalGroup(
            jProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jProductLayout.setVerticalGroup(
            jProductLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jProductLayout.createSequentialGroup()
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBoxController.add(jProduct);

        jEmployer.setBackground(new java.awt.Color(255, 204, 0));
        jEmployer.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jEmployerMouseMoved(evt);
            }
        });
        jEmployer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jEmployerMousePressed(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("Nhân viên");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/people-2-icon.png"))); // NOI18N

        javax.swing.GroupLayout jEmployerLayout = new javax.swing.GroupLayout(jEmployer);
        jEmployer.setLayout(jEmployerLayout);
        jEmployerLayout.setHorizontalGroup(
            jEmployerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEmployerLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jEmployerLayout.setVerticalGroup(
            jEmployerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jEmployerLayout.createSequentialGroup()
                .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBoxController.add(jEmployer);

        jPay.setBackground(new java.awt.Color(204, 102, 255));
        jPay.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jPayMouseMoved(evt);
            }
        });
        jPay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPayMouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Thanh toán");
        jLabel14.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/pay-icon.png"))); // NOI18N

        javax.swing.GroupLayout jPayLayout = new javax.swing.GroupLayout(jPay);
        jPay.setLayout(jPayLayout);
        jPayLayout.setHorizontalGroup(
            jPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPayLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPayLayout.setVerticalGroup(
            jPayLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPayLayout.createSequentialGroup()
                .addComponent(jLabel15, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jBoxController.add(jPay);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBoxController, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addComponent(jBoxHeader, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBoxHeader, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBoxController, javax.swing.GroupLayout.DEFAULT_SIZE, 349, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    ProductsManager PM;
    private void jProductMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductMousePressed
        PM = new ProductsManager(c, em);
        PM.setVisible(true);
    }//GEN-LAST:event_jProductMousePressed

    private void jProductMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jProductMouseMoved
        jProduct.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jProductMouseMoved

    private void jEmployerMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmployerMouseMoved
        jEmployer.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jEmployerMouseMoved

    private void jPayMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPayMouseMoved
        jPay.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_jPayMouseMoved
    PaysManager PMs;
    private void jPayMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPayMouseClicked
        PMs = new PaysManager(c, em);
        PMs.setVisible(true);
    }//GEN-LAST:event_jPayMouseClicked
    EmployeesManager EM;
    private void jEmployerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jEmployerMousePressed
        EM = new EmployeesManager(c, em);
        EM.setVisible(true);
    }//GEN-LAST:event_jEmployerMousePressed
//   chức năng liên quan đến tài khoản

    private void jAccMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jAccMouseClicked
        jAcc.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                jInteractAcc.show(e.getComponent(), e.getX(), e.getY());
            }

        });
    }//GEN-LAST:event_jAccMouseClicked

    private void jInforEmActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jInforEmActionPerformed
        new InforAcc(c, em).setVisible(true);
        
    }//GEN-LAST:event_jInforEmActionPerformed

    private void jLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jLogoutActionPerformed
        this.dispose();
        new login().setVisible(true);

    }//GEN-LAST:event_jLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Manager.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Employers e = new Employers();
                e.setId(1);
                new Manager(e).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel date;
    private javax.swing.JLabel dayOfWeek;
    private javax.swing.JLabel jAcc;
    private javax.swing.JLabel jAccName;
    private javax.swing.JPanel jBoxController;
    private javax.swing.JPanel jBoxHeader;
    private javax.swing.JPanel jEmployer;
    private javax.swing.JMenuItem jInforEm;
    private javax.swing.JPopupMenu jInteractAcc;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jLogout;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPay;
    private javax.swing.JPanel jProduct;
    private javax.swing.JLabel time;
    // End of variables declaration//GEN-END:variables
}
