/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Views.ProductsManager;

import javax.swing.JPanel;

/**
 *
 * @author ADMIN
 */
public class Products extends javax.swing.JFrame {

    /**
     * Creates new form Employer
     */
    public Products() {
        initComponents();
        ListPro listPro = new ListPro();
        setLayer(listPro);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void setLayer(JPanel panel){
        jLayeredPane1.removeAll();
        jLayeredPane1.add(panel);
        jLayeredPane1.repaint();
        jLayeredPane1.revalidate();
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jToolBar2 = new javax.swing.JToolBar();
        jCreatePro = new javax.swing.JButton();
        jListPro = new javax.swing.JButton();
        jUpdatePro = new javax.swing.JButton();
        jDeletePro = new javax.swing.JButton();
        jPrintPro = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jTabbedPane2 = new javax.swing.JTabbedPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sản Phẩm");

        jToolBar2.setRollover(true);

        jCreatePro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/add-1-icon.png"))); // NOI18N
        jCreatePro.setText("Thêm mới");
        jCreatePro.setFocusable(false);
        jCreatePro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jCreatePro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jCreatePro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCreateProActionPerformed(evt);
            }
        });
        jToolBar2.add(jCreatePro);

        jListPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/list-icon.png"))); // NOI18N
        jListPro.setText("Danh sách");
        jListPro.setFocusable(false);
        jListPro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jListPro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jListPro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jListProActionPerformed(evt);
            }
        });
        jToolBar2.add(jListPro);

        jUpdatePro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/edit-file-icon.png"))); // NOI18N
        jUpdatePro.setText("Cập nhật");
        jUpdatePro.setFocusable(false);
        jUpdatePro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jUpdatePro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jUpdatePro);

        jDeletePro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/Close-icon.png"))); // NOI18N
        jDeletePro.setText("Xóa");
        jDeletePro.setFocusable(false);
        jDeletePro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jDeletePro.setMaximumSize(new java.awt.Dimension(50, 49));
        jDeletePro.setMinimumSize(new java.awt.Dimension(50, 49));
        jDeletePro.setPreferredSize(new java.awt.Dimension(50, 49));
        jDeletePro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jDeletePro);

        jPrintPro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Commons/img/print-icon.png"))); // NOI18N
        jPrintPro.setText("In");
        jPrintPro.setFocusable(false);
        jPrintPro.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPrintPro.setMaximumSize(new java.awt.Dimension(50, 49));
        jPrintPro.setMinimumSize(new java.awt.Dimension(50, 49));
        jPrintPro.setPreferredSize(new java.awt.Dimension(50, 49));
        jPrintPro.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToolBar2.add(jPrintPro);

        jLayeredPane1.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 725, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 363, Short.MAX_VALUE)
        );

        jLayeredPane1.add(jPanel2, "card2");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLayeredPane1)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jToolBar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Sản Phẩm", jPanel1);
        jTabbedPane1.addTab("Thông tin chung", jTabbedPane2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jListProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jListProActionPerformed
        ListPro listPro = new ListPro();
        setLayer(listPro);
    }//GEN-LAST:event_jListProActionPerformed

    private void jCreateProActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCreateProActionPerformed
        CreatePro createPro = new CreatePro();
        setLayer(createPro);
    }//GEN-LAST:event_jCreateProActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Products.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Products().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jCreatePro;
    private javax.swing.JButton jDeletePro;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JButton jListPro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JButton jPrintPro;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JToolBar jToolBar2;
    private javax.swing.JButton jUpdatePro;
    // End of variables declaration//GEN-END:variables
}
